name: Check and Resolve Dependencies
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pip install pylint
          pipreqs > requirements.txt
          pip install -r requirements.txt

      - name: Analyze python codes with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
