name: Check and Resolve Dependencies
on:
  push:
    branches: [i190555]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Write requirements.txt test
      #   run: |
      #     pipreqs > requirements.txt
      # with:
      #   PROJECT_PATH: project_folder   #default is the root of the repository
      #   REQUIREMENT_PATH: project_folder/requirements.txt  #default is requirement.txt in the root of your repository

      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pip install pylint
          pipreqs > requirements.txt
          pip install -r requirements.txt
      - name: Analyze python codes with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
