name: Check and Resolve Dependencies
on:
  push:
    branches: [i190555]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      -name: Analyze python codes with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;

- name: Python Pylint GitHub Action
  uses: fylein/python-pylint-github-action@v1
  with:
    args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc
