name: Check and Resolve Dependencies
on:
  push:
    branches: [i190555]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      # - run: |
      #     check-manifest -v

      - name: Test code
        run: |
          pytest
